import R121340 from '../assets/servers/R121-340.png';
import E162220 from '../assets/servers/E162-220.png';
import E251U70 from '../assets/servers/E251-U70.png';
import E152 from '../assets/servers/E152.png';
import E252 from '../assets/servers/E252.png';
import G221Z30 from '../assets/servers/G221-Z30.png';
import G242 from '../assets/servers/G242.png';
import G591HS0 from '../assets/servers/G591-HS0.png';

import ProcyonLogo from '../assets/logos/Procyon-vertical.png';
import ParallaxSolutionsLogo from '../assets/logos/Parallax Solutions-vertical.png';

import { ServerFormFactor, ServerTier } from '../includes/Servers.interface';
import { CodiumMemory, CodiumMemory128, CodiumMemory256 } from './memory';
import { NetworkFiber, NetworkFiber10Gbps, Networking } from './network';
import { CodiumProcessor, CodiumProcessor64, CodiumProcessorQuantumX, CodiumProcessorX8 } from './processors';
import { CodiumStorage } from './storage';

export default [
    {
        manufacturer: 'Procyon',
        manufacturerLogoSrc: ProcyonLogo,
        model: 'R121-340',
        tier: ServerTier.ENTRY,
        imageSrc: R121340,
        formFactor: ServerFormFactor.ONE_U,
        cpu: new CodiumProcessor(),
        threadingFactor: 1,
        cpuAmount: 1,
        memory: new CodiumMemory(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 2,
        powerConsumption: 80,
        price: 1000,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'E152',
        tier: ServerTier.STANDARD,
        imageSrc: E152,
        formFactor: ServerFormFactor.ONE_U,
        cpu: new CodiumProcessor(),
        threadingFactor: 1,
        cpuAmount: 1,
        memory: new CodiumMemory(),
        storage: [new CodiumStorage(), new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 2,
        powerConsumption: 85,
        price: 1200,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'E162-220',
        tier: ServerTier.STANDARD,
        imageSrc: E162220,
        formFactor: ServerFormFactor.ONE_U,
        cpu: new CodiumProcessor64(),
        threadingFactor: 2,
        cpuAmount: 1,
        memory: new CodiumMemory(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 4,
        powerConsumption: 110,
        price: 2250,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'E251-U70',
        tier: ServerTier.STANDARD,
        imageSrc: E251U70,
        formFactor: ServerFormFactor.TWO_U,
        cpu: new CodiumProcessor64(),
        threadingFactor: 2,
        cpuAmount: 2,
        memory: new CodiumMemory(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 4,
        powerConsumption: 100,
        price: 2000,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'E252',
        tier: ServerTier.STANDARD,
        imageSrc: E252,
        formFactor: ServerFormFactor.TWO_U,
        cpu: new CodiumProcessor64(),
        threadingFactor: 2,
        cpuAmount: 2,
        memory: new CodiumMemory(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 4,
        powerConsumption: 140,
        price: 3250,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'G221-Z30',
        tier: ServerTier.PRO,
        imageSrc: G221Z30,
        formFactor: ServerFormFactor.TWO_U,
        cpu: new CodiumProcessorX8(),   
        threadingFactor: 2,
        cpuAmount: 2,
        memory: new CodiumMemory128(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 4,
        powerConsumption: 330,
        price: 12000,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'G242',
        tier: ServerTier.PRO,
        imageSrc: G242,
        formFactor: ServerFormFactor.THREE_U,
        cpu: new CodiumProcessorX8(),
        threadingFactor: 2,
        cpuAmount: 2,
        memory: new CodiumMemory128(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber()),
        networkPorts: 4,
        powerConsumption: 330,
        price: 12000,
    },
    {
        manufacturer: 'Parallax Solutions',
        manufacturerLogoSrc: ParallaxSolutionsLogo,
        model: 'G591-HS0',
        tier: ServerTier.QUANTUM,
        imageSrc: G591HS0,
        formFactor: ServerFormFactor.FIVE_U,
        cpu: new CodiumProcessorQuantumX(),
        threadingFactor: 2,
        cpuAmount: 4,
        memory: new CodiumMemory256(),
        storage: [new CodiumStorage()],
        network: new Networking(new NetworkFiber10Gbps()),
        networkPorts: 8,
        powerConsumption: 3300,
        price: 4200000,
    },
];